apiVersion: v1
kind: PersistentVolume
metadata:
  name: webscraper-data-pv
  labels:
    app: webscraper-api
    component: data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/webscraper-data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webscraper-data-pvc
  labels:
    app: webscraper-api
    component: data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webscraper-config-pv
  labels:
    app: webscraper-api
    component: config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/webscraper-config
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webscraper-config-pvc
  labels:
    app: webscraper-api
    component: config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi

---
# Alternative: Using dynamic storage provisioning
# Uncomment the following if you have a dynamic storage provisioner
#
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: webscraper-data-pvc-dynamic
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard  # or your storage class name
#   resources:
#     requests:
#       storage: 10Gi
#
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: webscraper-config-pvc-dynamic
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard  # or your storage class name
#   resources:
#     requests:
#       storage: 1Gi 