services:
  webscraper-api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Optional: Set OpenAI API key via environment variable
      # OPENAI_API_KEY: ${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      # Optional: Mount a volume for logs or data persistence
      - ./logs:/app/logs
    restart: unless-stopped
    container_name: webscraper-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - webscraper-network

networks:
  webscraper-network:
    driver: bridge

volumes:
  logs:
    driver: local 