version: '3.8'

services:
  webscraper-api:
    image: neobruenn/webscraper-api:1.2.2
    container_name: webscraper-api
    ports:
      - "8000:8000"
    environment:
      # Auto-detection for full compose setup
      DEPLOYMENT_MODE: full
      AUTO_DB_SETUP: true
      
      # Database connection for auto-configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: webscraper
      DB_USER: postgres_user
      DB_PASSWORD: secure_postgres_password
      DB_TABLE: proxies
      
      # Metrics configuration
      METRICS_ENABLED: ${METRICS_ENABLED:-true}
      PERSIST_METRICS: ${PERSIST_METRICS:-true}
      METRICS_DB_PATH: ${METRICS_DB_PATH:-data/metrics.db}
      MEMORY_RETENTION_HOURS: ${MEMORY_RETENTION_HOURS:-24}
      
      # API Key (can be overridden in .env file)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    volumes:
      - ../data:/app/data
    networks:
      - webscraper_full
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: webscraper-postgres
    environment:
      POSTGRES_DB: webscraper
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: secure_postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../scripts:/docker-entrypoint-initdb.d/
    networks:
      - webscraper_full
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d webscraper"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis for shared state in K8s environments
  # redis:
  #   image: redis:7-alpine
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 3

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@webscraper.local
      - PGADMIN_DEFAULT_PASSWORD=admin_password_2024
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - tools

volumes:
  # Named volumes for persistence
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  # redis_data:
  #   driver: local

networks:
  webscraper_full:
    driver: bridge 