apiVersion: apps/v1
kind: Deployment
metadata:
  name: webscraper-api
  labels:
    app: webscraper-api
spec:
  replicas: 3  # Multiple pods for load distribution
  selector:
    matchLabels:
      app: webscraper-api
  template:
    metadata:
      labels:
        app: webscraper-api
    spec:
      containers:
      - name: webscraper-api
        image: neoexec/webscraper-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: UVICORN_WORKERS
          value: "2"  # 2 workers per pod
        - name: UVICORN_WORKER_CLASS
          value: "uvicorn.workers.UvicornWorker"
        - name: MAX_THREAD_POOL_SIZE
          value: "10"  # Increased thread pool
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: webscraper-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        # Graceful shutdown
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
      # Pod disruption budget for rolling updates
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: webscraper-api-service
spec:
  selector:
    app: webscraper-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webscraper-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"  # 5 min timeout for scraping
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  rules:
  - host: webscraper.local  # Change to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webscraper-api-service
            port:
              number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: webscraper-secrets
type: Opaque
data:
  # Base64 encoded OpenAI API key
  # echo -n "sk-your-api-key" | base64
  openai-api-key: c2stdGVzdC1hcGkta2V5  # Replace with your base64 encoded key
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webscraper-api-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: webscraper-api 